### ISSUE TITLE
What is polygon yolov5 mAP on UCAS dataset 

### ISSUE THREAD

**Issue by vpeopleonatank** [XinzeLee/PolygonObjectDetection#1]
Firstly, thanks for your work.
I have question. Did you test poly-yolo5 model on UCAS? As I want to compare it 's result with other object detectors. There are currently some sota  satellite image related object detectors 's results in this repo https://github.com/ming71/UCAS-AOD-benchmark

**Comment by XinzeLee** [comment]
Thank you for your interests! Actually, the exemplar dataset is the UCAS-AOD dataset. And all the performance indicators given in the README.md are the indicators for UCAS-AOD. And I have attached a result here for your reference. https://user-images.githubusercontent.com/87064748/125021771-ddcb8a00-e0ad-11eb-8a4e-bef79280c258.png. Also, if you want to compare those two repos, I strongly suggest you to take a look at the computation of MAP in the two repos. Since my repo and ming71's repo may have different computation towards the MAP performance.

**Comment by vpeopleonatank** [comment]
Thanks for clarification. I 'll check it.
